name = "worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = "661484bfa811d50ad0a7c946485ad9ae"
route = ""
zone_id = "821cee03d4ed98382ae44898382d29dc"

[build.upload]
# Upload the code directly from the src directory.
dir = "src"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "GAME", class_name = "Game"}]
